### PR TITLE
web page beta version

### PR DESCRIPTION
**Pull request by Bindusar1212**
by using  following
- html
- bootstrap
- css
- js

PIC1

### CODE REVIEW

**Comment by pushpinderpalsingh** [comment]
Have we hosted this on Github Pages yet? @anubhavsingh16 @Bindusar1212

**Comment by anubhavsingh16** [comment]
No but we are planning to 🥰

**Comment by pushpinderpalsingh** [comment]
Isko host kar lete hai. Abhi ss me toh design acha lag raha hai

**Comment by anubhavsingh16** [comment]
@pushpinderpalsingh any feedback to @Bindusar1212

**Comment by anubhavsingh16** [comment]
I think the margin between definition of open source and hackathon is quite less and month class is not properly aligned.

**Comment by anubhavsingh16** [comment]
Design is quite nice and clean. but some minor changes are required.  
@pushpinderpalsingh can we merge this PR and open issue for the public which I mentioned above?

**Comment by pushpinderpalsingh** [comment]
Sure, Ya design is quite nice. Let's merge this PR and make setting up GitHub pages as a priority

**Comment by Bindusar1212** [comment]
thanku @anubhavsingh16  @pushpinderpalsingh

**Pull request merged**
